project:
  render:
    - index.qmd
server: shiny
format:
  dashboard:
    logo: https://upload.wikimedia.org/wikipedia/fr/1/10/Logo_Insee.svg
    nav-buttons: github
    theme: [yeti, style/custom.scss]
